
-- добавление тестовых пунктов отправки / доставки
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №1', 'Уфа, пр.Октября 11', '450001', '+7 (347) 123-45-67', 'dep1@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №2', 'Уфа, пр.Октября 110', '450010', '+7 (347) 765-43-21', 'dep2@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №3', 'Уфа, ул.Айская 17', '450015', '+7 (347) 000-11-22', 'dep3@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №4', 'Уфа, ул.50-летия Октября 17', '450005', '+7 (347) 222-11-00', 'dep4@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №5', 'Уфа, ул.Мустая Карима 5', '450025', '+7 (347) 012-34-56', 'dep5@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №6', 'Уфа, ул.Революционная 8', '450005', '+7 (347) 101-01-01', 'dep6@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №7', 'Уфа, ул.Пархоменко 34', '450008', '+7 (347) 100-10-10', 'dep7@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №8', 'Уфа, ул.Карла Маркса 10', '450002', '+7 (347) 200-20-20', 'dep8@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №9', 'Уфа, ул.Ленина 4', '450003', '+7 (347) 777-77-77', 'dep9@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №10', 'Уфа, ул.Достоевского 13', '450018', '+7 (347) 155-15-15', 'dep10@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №11', 'Уфа, ул.50 лет СССР 1', '450013', '+7 (347) 454-54-54', 'dep11@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №12', 'Уфа, ул.Менделеева 112', '450114', '+7 (347) 111-11-11', 'dep12@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №13', 'Уфа, ул.Менделеева 21', '450110', '+7 (347) 000-10-10', 'dep13@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №14', 'Уфа, ул.Жукова 27', '450010', '+7 (347) 888-88-88', 'dep14@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №15', 'Уфа, ул.Бакалинская 1', '450077', '+7 (347) 777-88-88', 'dep15@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №16', 'Уфа, ул.Кирова 52', '450007', '+7 (347) 123-77-88', 'dep16@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №17', 'Уфа, ул.Мингажева 6', '450005', '+7 (347) 800-80-80', 'dep17@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №18', 'Уфа, ул.Степана Кувукина 36', '450019', '+7 (347) 700-70-80', 'dep18@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №19', 'Уфа, ул.Армавирская 10', '450019', '+7 (347) 700-70-70', 'dep19@ap.com');
insert into "deliverypoint" (id, name, address, postcode, phone, email) values (nextval('sq_deliverypoint'), 'Отделение №20', 'Уфа, пр.Мира 10', '450015', '+7 (347) 800-80-80', 'dep20@ap.com');

-- добавление тестовых клиентов
insert into "customer" (id, name, first_name, last_name, middle_name, address, phone, email, type, createddt, createdby_id) values (nextval('sq_customer'), '', 'Иван', 'Иванов', 'Иванович', 'Уфа, пр.Мира 1', '+7 (922) 123-45-67', 'ivanov@ap.com', 0, current_date, (select last_value from sq_user));
insert into "customer" (id, name, first_name, last_name, middle_name, address, phone, email, type, createddt, createdby_id) values (nextval('sq_customer'), '', 'Петр', 'Петров', 'Петрович', 'Уфа, ул.Менделеева 2', '+7 (922) 777-77-77', 'petrov@ap.com', 0, current_date, (select last_value from sq_user));
insert into "customer" (id, name, first_name, last_name, middle_name, address, phone, email, type, createddt, createdby_id) values (nextval('sq_customer'), 'ООО "Рога и Копыта"', '', '', '', 'Уфа, ул.Ленина 7', '+7 (347) 808-88-88', 'roga@ap.com', 1, current_date, (select last_value from sq_user));
insert into "customer" (id, name, first_name, last_name, middle_name, address, phone, email, type, createddt, createdby_id) values (nextval('sq_customer'), 'ООО "Алешкин и Ко"', '', '', '', 'Уфа, ул.Рабкоров 52', '+7 (347) 100-77-77', 'aleshkin@ap.com', 1, current_date, (select last_value from sq_user));

commit;

-- добавление тестовых заказов
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '00000-00000-00000-00000', (select last_value from sq_customer), (select last_value from sq_deliverypoint)-1, (select last_value from sq_deliverypoint)-2, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '00000-00000-00000-11111', (select last_value from sq_customer), (select last_value from sq_deliverypoint)-2, (select last_value from sq_deliverypoint)-3, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '00000-00000-00000-22222', (select last_value from sq_customer), (select last_value from sq_deliverypoint)-3, (select last_value from sq_deliverypoint)-4, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '00000-00000-11111-00000', (select last_value from sq_customer)-1, (select last_value from sq_deliverypoint)-4, (select last_value from sq_deliverypoint)-5, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '00000-00000-22222-00000', (select last_value from sq_customer)-1, (select last_value from sq_deliverypoint)-5, (select last_value from sq_deliverypoint)-6, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '00000-00000-33333-00000', (select last_value from sq_customer)-1, (select last_value from sq_deliverypoint)-6, (select last_value from sq_deliverypoint)-7, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '00000-11111-00000-00000', (select last_value from sq_customer)-2, (select last_value from sq_deliverypoint)-7, (select last_value from sq_deliverypoint)-8, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '00000-22222-00000-00000', (select last_value from sq_customer)-2, (select last_value from sq_deliverypoint)-8, (select last_value from sq_deliverypoint)-9, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '00000-33333-00000-00000', (select last_value from sq_customer)-2, (select last_value from sq_deliverypoint)-9, (select last_value from sq_deliverypoint)-10, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '11111-00000-00000-00000', (select last_value from sq_customer)-3, (select last_value from sq_deliverypoint)-10, (select last_value from sq_deliverypoint)-11, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '22222-00000-00000-00001', (select last_value from sq_customer)-3, (select last_value from sq_deliverypoint)-11, (select last_value from sq_deliverypoint)-12, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));
insert into "order" (id, barcode, customer_id,  from_point,  to_point,  createddt,  createdby_id,  modifieddt,  modifiedby_id) values (nextval('sq_order'), '33333-00000-00000-00002', (select last_value from sq_customer)-3, (select last_value from sq_deliverypoint)-12, (select last_value from sq_deliverypoint)-13, current_date, (select last_value from sq_user), current_date, (select last_value from sq_user));